name: Sadellari DAO CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  test-contracts:
    name: Test Solana Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor avm --locked --force && avm install latest && avm use latest

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Lint Contracts
        run: cargo clippy --all-targets -- -D warnings

      - name: Build Contracts
        run: anchor build

  test-typescript:
    name: Test TypeScript Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['sdk', 'slack-api']
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install
        working-directory: ${{ github.workspace }}
        
      - name: Lint
        run: pnpm lint
        working-directory: packages/${{ matrix.package }} || apps/api/${{ matrix.package }}

      - name: Run Tests
        run: pnpm test
        working-directory: packages/${{ matrix.package }} || apps/api/${{ matrix.package }}

      - name: Build Package
        run: pnpm build
        working-directory: packages/${{ matrix.package }} || apps/api/${{ matrix.package }}
